# Generated by Django 4.2 on 2023-07-26 13:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0003_viberuser_menu_alter_viberuser_viber_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Активований'), ('1', 'Деактивований')], default=0, max_length=1, verbose_name='Стан')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='viber_bot.service')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
