# Generated by Django 4.2 on 2023-07-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0004_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
