# Generated by Django 4.2 on 2023-07-27 09:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0006_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='viber_bot.service', verbose_name='Батьківська послуга'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Активований'), ('1', 'Деактивований')], default=0, max_length=1, verbose_name='Стан')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='viber_bot.settlement', verbose_name='Батьківське розташування')),
            ],
            options={
                'verbose_name': 'Розташування',
                'verbose_name_plural': 'Розташування',
            },
        ),
    ]
