# Generated by Django 4.2 on 2023-07-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0008_settlement_codifier_alter_settlement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='type_code',
            field=models.CharField(blank=True, choices=[('0', 'Активований'), ('1', 'Деактивований')], max_length=1, null=True, verbose_name='Тип'),
        ),
    ]
