# Generated by Django 4.2 on 2023-07-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0010_alter_settlement_type_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Активований'), ('1', 'Деактивований')], default=0, max_length=1, verbose_name='Стан')),
                ('number', models.CharField(blank=True, max_length=19, verbose_name='Назва')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests_customer', to='viber_bot.viberuser', verbose_name='Замовник')),
                ('executors', models.ManyToManyField(related_name='service_requests_executors', to='viber_bot.viberuser', verbose_name='Виконавці')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
