# Generated by Django 4.2 on 2023-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0011_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Адреса'),
        ),
    ]
