# Generated by Django 4.2 on 2023-07-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0012_viberuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='settlement',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests_settlement', to='viber_bot.settlement', verbose_name='Населений пункт'),
            preserve_default=False,
        ),
    ]
