# Generated by Django 4.2 on 2023-08-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0014_servicerequest_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settlement',
            new_name='Position',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='settlement',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='position',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests_position', to='viber_bot.position', verbose_name='Населений пункт'),
            preserve_default=False,
        ),
    ]
