# Generated by Django 4.2 on 2023-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0015_rename_settlement_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(default='http://127.0.0.1:8000/static/images/service.png', verbose_name='URL зображення'),
            preserve_default=False,
        ),
    ]
