# Generated by Django 4.2 on 2023-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0016_service_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='position',
            field=models.ManyToManyField(related_name='viber_user_position', to='viber_bot.position', verbose_name='Розташування'),
        ),
    ]
