# Generated by Django 4.2 on 2023-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0017_viberuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='executor',
            field=models.BooleanField(default=False),
        ),
    ]
