# Generated by Django 4.2 on 2023-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0020_alter_position_codifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Активований'), ('1', 'Деактивований')], default=0, max_length=1, verbose_name='Стан')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
