# Generated by Django 4.2 on 2023-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0022_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default='file', max_length=100, verbose_name='Назва файлу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user_viber_id',
            field=models.CharField(default='file', max_length=100, verbose_name='Вайбер ідентифікатор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads_viber/', verbose_name='Файл'),
        ),
    ]
