# Generated by Django 4.2 on 2023-08-24 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0023_uploadedfile_file_name_uploadedfile_user_viber_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='columns',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Колонки'),
        ),
        migrations.AddField(
            model_name='service',
            name='rows',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Рядки'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads_viber_bot/', verbose_name='Файл'),
        ),
    ]
