# Generated by Django 4.2 on 2023-08-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0024_service_columns_service_rows_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='file',
            field=models.FileField(default='file', upload_to='viber_bot_buttons/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
