# Generated by Django 4.2 on 2023-08-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0025_service_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='file',
            new_name='image',
        ),
    ]
