# Generated by Django 4.2 on 2023-08-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0027_remove_service_image_url_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Пріорітет'),
        ),
    ]
