# Generated by Django 4.2 on 2023-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0029_viberuser_customer_rating_viberuser_executor_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Підтверджена'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rejected_executors',
            field=models.ManyToManyField(related_name='service_requests_rejected_executors', to='viber_bot.viberuser', verbose_name='Відхилені Виконавці'),
        ),
    ]
