# Generated by Django 4.2 on 2023-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0030_servicerequest_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='rejected_executors',
            field=models.ManyToManyField(blank=True, null=True, related_name='service_requests_rejected_executors', to='viber_bot.viberuser', verbose_name='Відхилені Виконавці'),
        ),
    ]
