# Generated by Django 4.2 on 2023-09-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0032_alter_servicerequest_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='number',
            field=models.CharField(blank=True, max_length=19, verbose_name='Номер'),
        ),
    ]
