# Generated by Django 4.2 on 2023-09-20 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0034_alter_servicerequest_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='modifiedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата змін'),
            preserve_default=False,
        ),
    ]
