# Generated by Django 4.2 on 2023-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0035_servicerequest_modifiedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон'),
        ),
    ]
