# Generated by Django 4.2 on 2023-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0037_alter_servicerequest_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='rejected_executors',
            field=models.ManyToManyField(blank=True, related_name='service_requests_rejected_executors', to='viber_bot.viberuser', verbose_name='Відхилені Виконавці'),
        ),
    ]
