# Generated by Django 4.2 on 2023-09-25 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0038_alter_servicerequest_rejected_executors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status_code',
            field=models.CharField(choices=[('0', 'Створена'), ('1', 'В роботі'), ('2', 'Виконана'), ('3', 'Скасована'), ('4', 'Очікування майстра'), ('5', 'Очікування підтвердження'), ('6', 'В роботі (Підтверджений майстер)'), ('7', 'Уточнення (від майстра)'), ('8', 'Уточнення (від клієнта)'), ('9', 'Завершено')], default=0, max_length=1, verbose_name='Стан'),
        ),
        migrations.AlterField(
            model_name='viberuser',
            name='customer_rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг клієнта'),
        ),
        migrations.AlterField(
            model_name='viberuser',
            name='executor_rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг майстра'),
        ),
    ]
