# Generated by Django 4.2 on 2023-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0039_alter_servicerequest_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='system_administrator',
            field=models.BooleanField(default=False, verbose_name='Системний адміністратор'),
        ),
    ]
