# Generated by Django 4.2 on 2023-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0040_viberuser_system_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='productnumber',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Код продукту'),
        ),
    ]
