# Generated by Django 4.2 on 2023-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0041_service_productnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='productnumber',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код продукту'),
        ),
    ]
