# Generated by Django 4.2.6 on 2023-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0042_alter_service_productnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Назва'),
        ),
    ]
