# Generated by Django 4.2.6 on 2024-01-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0045_alter_position_codifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Активований'), ('1', 'Деактивований')], default=0, max_length=1, verbose_name='Стан')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листи',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Активований'), ('1', 'Деактивований')], default=0, max_length=1, verbose_name='Стан')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_price_list', to='viber_bot.pricelist', verbose_name='Прайс-лист')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_service', to='viber_bot.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайси',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_price_list', to='viber_bot.pricelist', verbose_name='Прайс-лист'),
        ),
    ]
