# Generated by Django 4.2.6 on 2024-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0049_alter_servicerequest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status_code',
            field=models.CharField(choices=[('0', 'Створена'), ('1', 'В роботі'), ('2', 'Виконана'), ('3', 'Скасована'), ('4', 'Очікування майстра'), ('5', 'Очікування підтвердження'), ('6', 'В роботі (Підтверджена та оплачена)'), ('7', 'Уточнення (від майстра)'), ('8', 'Уточнення (від клієнта)'), ('9', 'Завершено')], default=0, max_length=1, verbose_name='Стан'),
        ),
    ]
