# Generated by Django 4.2.6 on 2024-03-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0050_alter_servicerequest_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_price_list', to='viber_bot.pricelist', verbose_name='Прайс-лист'),
        ),
    ]
