# Generated by Django 4.2.6 on 2024-07-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0051_alter_position_price_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViberUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Активований'), ('1', 'Деактивований')], default=0, max_length=1, verbose_name='Стан')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Назва')),
                ('rating1', models.PositiveIntegerField(default=1)),
                ('rating2', models.PositiveIntegerField(default=1)),
                ('average_rating', models.FloatField(editable=False)),
                ('viber_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viber_user_rating', to='viber_bot.viberuser', verbose_name='Користувач Viber')),
            ],
        ),
    ]
