# Generated by Django 4.2.6 on 2024-07-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0052_viberuserrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viberuserrating',
            options={'verbose_name': 'Оцінка користувача Viber', 'verbose_name_plural': 'Оцінка користувачів Viber'},
        ),
    ]
