# Generated by Django 4.2.6 on 2024-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0053_alter_viberuserrating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuserrating',
            name='type_rating',
            field=models.CharField(choices=[('0', 'Майстер'), ('1', 'Клієнт')], default=0, max_length=1, verbose_name='Тип оцінки'),
        ),
    ]
