# Generated by Django 4.2.6 on 2024-07-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0054_viberuserrating_type_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва'),
        ),
    ]
