# Generated by Django 4.2.6 on 2024-08-18 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viber_bot', '0055_price_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Остання активність'),
        ),
    ]
