# Generated by Django 4.2 on 2023-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status_code', models.CharField(choices=[('0', 'Чернетка'), ('1', 'Очікує обробки'), ('2', 'Оброблено'), ('3', 'Очікує відправки'), ('4', 'Відправлено')], default=0, max_length=1, verbose_name='Стан')),
                ('identifier', models.CharField(max_length=64, verbose_name='Ідентифікатор')),
                ('direction', models.CharField(choices=[('0', 'Вхідний'), ('1', 'Вихідний')], max_length=1, verbose_name='Напрямок')),
                ('body', models.TextField(verbose_name='Тіло пакету')),
                ('version', models.CharField(max_length=32, verbose_name='Версія')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='Пріорітет')),
                ('type', models.CharField(max_length=64, verbose_name='Тип')),
                ('contentType', models.CharField(max_length=32, verbose_name='Тип вмісту')),
                ('operation', models.CharField(max_length=16, verbose_name='Операція')),
            ],
            options={
                'verbose_name': 'Rabbit: Пакет',
                'verbose_name_plural': 'Rabbit: Пакети',
            },
        ),
    ]
