# Generated by Django 4.2 on 2023-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbitpackage',
            name='last_error',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Остання помилка'),
        ),
    ]
