# Generated by Django 4.2 on 2023-08-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0002_rabbitpackage_last_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitpackage',
            name='status_code',
            field=models.CharField(choices=[('0', 'Чернетка'), ('1', 'Очікує обробки'), ('2', 'Оброблено'), ('3', 'Очікує відправки'), ('4', 'Відправлено'), ('5', 'Помилка')], default=0, max_length=1, verbose_name='Стан'),
        ),
    ]
